feat: add new subpage
Ervige/orderofthephoenix pull request #48
Opened 2024-05-26 18:25 UTC by Ervige

2024-05-26 19:20 UTC, lukasz-rdzanek requested changes
Fix issues in comments

2024-05-26 19:20 UTC, lukasz-rdzanek commented on pages/housePrideQuiz/hufflepuff/hufflepuffNewt.html
> +                >Children's Privacy Policy</a
This </a> close tag should go to next line

2024-05-26 19:20 UTC, lukasz-rdzanek commented on pages/housePrideQuiz/hufflepuff/hufflepuffNewt.html
> +                >Legals</a
Same as above

2024-05-26 19:47 UTC, Ervige commented on pages/housePrideQuiz/hufflepuff/hufflepuffNewt.html
> +                >Children's Privacy Policy</a
@lukasz-rdzanek fixed

2024-05-26 19:47 UTC, Ervige commented on pages/housePrideQuiz/hufflepuff/hufflepuffNewt.html
> +                >Legals</a
@lukasz-rdzanek fixed

2024-05-27 06:08 UTC, lukasz-rdzanek approved these changes

2024-05-27 06:08 UTC, merged